### ISSUE TITLE
B3 vertical positioning is not responsive

### ISSUE THREAD

**Issue by pietgeursen** [BeepBoopBot/BeepBoopBot#122]
To replicate: 
1. Open page
2. Open the dev console. The board resizes but B3 is not moved onto the board.
3. Click an action button, b3 moves to the starting tile.
4. Close the dev console. B3 is in the wrong place.
5. Click a button, B3 moves to the correct tile.

**Comment by troys-code** [comment]
B3 positioning is now responsive. The robot component is forced to re-render when the window is resized.
