### ISSUE TITLE
Reviving demo page

### ISSUE THREAD

**Issue by troys-code** [BeepBoopBot/BeepBoopBot#180]
Hey folks,

@vaishnavi-iyer @Olwiba @sean-johnson @miles-fitzsimons 

I'm back in NZ and networking a bit.

This project is the best example of my web dev experience.

I'm working to publish it again, will probably use free public hosting like surge.sh
ETA is 1-2 days.

Feel free to reach out if you have any input or anything.

Cheers,
Troy

**Comment by vaishnavi-iyer** [comment]
Hey Troy,

Good to hear from you. I have moved to Australia a few months back
otherwise would have loved to network.

Good idea on publishing, let me know if you need any hand.

Cheers,
Vai

**Comment by Olwiba** [comment]
Hey!

Awesome to see this back from the grave 🙂 Happy to help if we need
anything or if it needs a little upgrade

I'm around Wellington at the moment if you wanted to grab a coffee/beer
and catch up

No stress either way

Ollie

**Comment by troys-code** [comment]
I got the webpage hosted here https://beepboopbot.github.io/BeepBoopBot/index.html (not playable yet)

It's trying to fetch bundle.js though...

Previously we had the `beepboopbot.com` domain, which is taken now and looks too pricey to bother with.

I would buy a different domain like `beepboopbot.(insert a good game domain here)`

Could one of you guys purchase that? My nz bank account doesn't have money on it yet.
I'm also asking my dad to send me the $25 for it so no worries if no one can help.

Would just like to get it soon in-case someone else snaps it up.

EDIT: I got https://beepboopbot.app

**Comment by troys-code** [comment]
It's deployed now, not to the domain though.

How I deployed:

```
npm install --global surge
surge webpage/ beepboopbot.surge.sh
```

Example output:

```
@troy-lamerton ➜ /workspaces/BeepBoopBot (master) $ surge webpage/

   Running as troy.lamerton@gmail.com (Student)

        project: webpage/
         domain: beepboopbot.surge.sh
         upload: [====================] 100% eta: 0.0s (49 files, 3551353 bytes)
            CDN: [====================] 100%
     encryption: *.surge.sh, surge.sh (62 days)
             IP: 138.197.235.123

   Success! - Published to beepboopbot.surge.sh
```

**Comment by troys-code** [comment]
https://beepboopbot.surge.sh/

Yeah it works on my machine - MacOS Chrome

Comment and reopen if it doesn't work on your phone or computer.
