### ISSUE TITLE
Choosing a level then completing it - Level doesn't advance to the next one

### ISSUE THREAD

**Issue by troys-code** [BeepBoopBot/BeepBoopBot#74]
Try choosing a level, then win the level.

Close the modal box and a lot of the buttons don't work anymore.

**Comment by miles-fitzsimons** [comment]
I think you've sorted this? Please close if so. Thanks. M

**Comment by troys-code** [comment]
Resolved by parsing ints before adding them together. A string of the current level was being concatenated with 1.
